package controllers;

public class StaticData {
	public static String[] feedLinks = {
		"http://feeds.feedburner.com/TechCrunch/", 
		"http://www.wpxi.com/feeds/categories/news/",
		"http://rss.cnn.com/rss/si_topstories.rss",
		"http://feeds.feedburner.com/ChicagoBreakingSports",
		"http://sports.espn.go.com/espn/rss/news",
		"http://rss.cnn.com/rss/money_latest.rss",
		"http://online.wsj.com/xml/rss/3_7014.xml",
		"http://www.economist.com/topics/us-economy/index.xml",
		
		"http://rss.cnn.com/rss/cnn_allpolitics.rss",
		"http://rss.cnn.com/rss/cnn_travel.rss",
		"http://rss.cnn.com/rss/cnn_showbiz.rss",
		"http://www.mtv.com/rss/news/news_full.jhtml",
		"http://feeds.ew.com/entertainmentweekly/music",
		"http://www.mtv.com/rss/news/movies_full.jhtml",
		"http://feeds.ew.com/entertainmentweekly/books",
		"http://www.engadget.com/rss.xml",
		
		"http://feeds.cbsnews.com/tech_talk",
		"http://www.wpxi.com/feeds/categories/events/",
		"http://www.wpxi.com/feeds/categories/news",
		"http://feeds.chicagotribune.com/chicagotribune/cars/",
		"http://news.yahoo.com/fashion/",
		"http://feeds.nytimes.com/nyt/rss/FashionandStyle",
		"http://www.wwd.com/rss/2/news/fashion",
		"http://feeds.feedburner.com/epicurious/epiblog",
		
		"http://news.yahoo.com/rss/",
		"http://feeds.cbsnews.com/CBSNewsMain",
		"http://feeds.feedburner.com/EducationWeekCurriculumAndLearning",
		"http://feeds.eonline.com/eonline/celebnews",
		"http://rss.firstshowing.net/firstshowing",
		
		//Added :AJ
		"http://feeds.bbci.co.uk/news/rss.xml",
		"http://feeds.bbci.co.uk/news/education/rss.xml",
		"http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
		"http://feeds.bbci.co.uk/news/business/rss.xml",
		"http://feeds.bbci.co.uk/news/health/rss.xml",
		
		//Added :AJ
		"http://www.reddit.com/.rss",
		
		//More Added
"http://feeds.nytimes.com/nyt/rss/HomePage",
"http://feeds.washingtonpost.com/wp-dyn/rss/linkset/2005/03/24/LI2005032400102_xml",
"http://hosted.ap.org/lineups/USHEADS-rss_2.0.xml?SITE=RANDOM&SECTION=HOME",
"http://rssfeeds.usatoday.com/usatoday-NewsTopStories",
"http://www.npr.org/rss/rss.php?id=1001",
"http://feeds.reuters.com/reuters/topNews",
"http://newsrss.bbc.co.uk/rss/newsonline_world_edition/americas/rss.xml",
"http://feeds.sltrib.com/mngi/rss/CustomRssServlet/297/200965.xml",
"http://www.deseretnews.com/home/index.rss",
"http://www.ksl.com/xml/148.rss",
"http://le.utah.gov/rss/utleg.xml",
"http://www.utah.gov/whatsnew/rss.xml",
"http://feeds.feedburner.com/standard/frontpage",
"http://www.thespectrum.com/rssfeeds/topstories.xml",
"http://topics.nytimes.com/top/news/national/usstatesterritoriesandpossessions/utah/index.html?inline=nyt-geo&rss=1",
"http://www.uen.org/feeds/rss/news.xml.php",
"http://www2.ed.gov/rss/edgov.xml",
"http://feeds.nytimes.com/nyt/rss/Education",
"http://www.smartbrief.com/servlet/rss?b=ASCD",
"http://www.pbs.org/teachers/learning.now/rss2/index.xml",
"http://www.npr.org/rss/rss.php?id=1013",
"http://www.techlearning.com/RSS",
"http://hosted.ap.org/lineups/SCIENCEHEADS-rss_2.0.xml?SITE=OHLIM&SECTION=HOME",
"http://feeds.sciencedaily.com/sciencedaily",
"http://feeds.nature.com/nature/rss/current",
"http://www.nasa.gov/rss/image_of_the_day.rss",
"http://www.techlearning.com/RSS",
"http://feeds.wired.com/wired/index",
"http://feeds.nytimes.com/nyt/rss/Technology",
"http://www.npr.org/rss/rss.php?id=1019",
"http://feeds.feedburner.com/time/gadgetoftheweek",
"http://feeds.surfnetkids.com/SurfingTheNetWithKids",
"http://rss.macworld.com/macworld/feeds/main",
"http://feeds.pcworld.com/pcworld/latestnews",
"http://rss.feedsportal.com/c/270/f/3547/index.rss",
"http://www.pbs.org/wgbh/pages/frontline/rss/files.xml",
"http://feeds.pbs.org/pbs/nbr-programs",
"http://www.pbs.org/wgbh/nova/rss/nova.xml",
"http://www.loc.gov/rss/read/eca.xml",
"http://feeds.feedburner.com/WeeklyReaderFeed/",
"http://feeds.reference.com/DictionarycomWordOfTheDay",
"http://feeds.feedburner.com/time/photoessays",
"http://www.sciencenewsforkids.org/rss/SNK.asp",
"http://hosted.ap.org/lineups/SPORTSHEADS-rss_2.0.xml?SITE=VABRM&SECTION=HOME",
"http://rss.cnn.com/rss/si_topstories.rss",
"http://feeds1.nytimes.com/nyt/rss/Sports",
"http://sports.yahoo.com/top/rss.xml",
"http://www.nba.com/jazz/rss.xml",
"http://feeds.sltrib.com/mngi/rss/CustomRssServlet/297/203308.xml",
"http://www.npr.org/rss/rss.php?id=1008",
"http://feeds.nytimes.com/nyt/rss/SundayBookReview",
"http://feeds2.feedburner.com/cartoonbank",
"http://www.npr.org/rss/rss.php?id=13",
"http://www.npr.org/rss/rss.php?id=1045",
"http://www.nationalgeographic.com/adventure/nga.xml",
"http://feeds.feedburner.com/TheDailyPuppy",
"http://davidkphotography.com/index.php?x=rss",
"http://feeds.feedburner.com/animals",
"http://feeds.feedburner.com/time/photoessays",
"http://feeds.feedburner.com/time/potw",
		
//Single Added
"http://www2.netflix.com/Top100RSS"
	};
	
	public static String[] feedImageUrls = {
		"http://www.xconomy.com/wordpress/wp-content/images/2011/09/techcrunch-logo.png",
		"http://media.cmgdigital.com/shared/media/web/site/www_wpxi_com/images/logo.png",
		"http://www.therecapp.com/content/art/app/icons/cnn_icon.jpg",
		"http://www.tbwe.com/pub/categoryitems/Chicago_Tribune_tn.jpg",
		"http://eclipse.tv/channels/espn.png",
		"http://www.therecapp.com/content/art/app/icons/cnn_icon.jpg",
		"http://img-android.lisisoft.com/imgmic/5/3/1335-i-wsj.reader_sp.jpg",
		"http://androiiid.com/wp-content/uploads/2011/07/bf1b1798f24732e3.png.png",
		
		"http://www.therecapp.com/content/art/app/icons/cnn_icon.jpg",
		"http://www.therecapp.com/content/art/app/icons/cnn_icon.jpg",
		"http://www.therecapp.com/content/art/app/icons/cnn_icon.jpg",
		"http://4.bp.blogspot.com/_1O-tdjVD-u8/TRMnnyPfJKI/AAAAAAAAD7U/9uhtq50RIRc/s1600/mtv.jpg",
		"http://static.wix.com/media/5200e1d38ea5f1f2aa6269b15776b466.wix_mp_256",
		"http://4.bp.blogspot.com/_1O-tdjVD-u8/TRMnnyPfJKI/AAAAAAAAD7U/9uhtq50RIRc/s1600/mtv.jpg",
		"http://static.wix.com/media/5200e1d38ea5f1f2aa6269b15776b466.wix_mp_256",
		"http://p.xbmcaddonbrowser.com/img/icons/plugin.video.engadget.png",
		
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://media.cmgdigital.com/shared/media/web/site/www_wpxi_com/images/logo.png",
		"http://media.cmgdigital.com/shared/media/web/site/www_wpxi_com/images/logo.png",
		"http://www.tbwe.com/pub/categoryitems/Chicago_Tribune_tn.jpg",
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://a0.twimg.com/profile_images/1488203320/skmr_256.png",
		"http://25.media.tumblr.com/avatar_d68bd8446787_128.png",
		"http://si3.twimg.com/profile_images/1015048338/epi-twitter-icon_reasonably_small.png",
		
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		
		
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		//REMOVE THERE
		"http://images.seroundtable.com/yahoo-slurp-1316437281.png",
		"http://microwaveadvances.com/television%20logos/cbs.png",
		"http://profile.ak.fbcdn.net/hprofile-ak-snc4/41565_5887538795_5127_q.jpg",
		"http://a2.twimg.com/profile_images/1669862831/elog_reasonably_small.jpg",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif",
		"http://widgets.markosweb.com/sb/new/f/i/r/firstshowing.net.gif"
		
		
	};

	public static String[] feedNames = {
		"TechCrunch",
		"Pittsburgh_Local_News",
		"CNN",
		"Chicago_Breaking_Sports_News",
		"ESPN",
		"CNN_Money",
		"Washington_Journal",
		"Economist",
		
		"CNN_Politics",
		"CNN_Travel",
		"CNN_Entertainment",
		"MTV",
		"Entertainment_Weekly",
		"MTV_Movies",
		"Entertainment_Weekly",
		"Engadget",
		
		"CBS_News",
		"Pittsburgh_Local_Events",
		"Pittsburgh_Local_News",
		"Chicago_Tribune_Auto",
		"Yahoo_Fashion",
		"New_York_Times_Fashion",
		"Women's _Wear_Daily_Fashion",
		"Epicurious",
		
		"Yahoo_News",
		"CBS_News",
		"Education_Week",
		"E!_Online_Celebrity_News",
		"First_Showing_Movie_News",
		
		"BBCTop",
		"BBCEducation",
		"BBCScience",
		"BBCBusiness",
		"BBCHealth",
		"Reddit",
		
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		
	};
	public static String[] feedCategories = {"Technology", 
		"Local",
		"Sports",
		"Sports",
		"Sports",
		"Business",
		"Finance",
		"Finance",
		
		"Politics",
		"Travel",
		"Entertainment",
		"Entertainment",
		"Music",
		"Movies",
		"Books",
		
		"Technology",
		"Technology",
		"Local",
		"Local",
		"Cars",
		"Fashion",
		"Fashion",
		"Fashion",
		"Food",
		
		"Generic",
		"Generic",
		"Education",
		"Celebrities",
		"Movies",
		
		"News",
		"Education",
		"Science",
		"Business",
		"Health",
		
		"Social",
		
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		"PlaceHolder",
		
	};
	
}
